import tractor from './images/images.jpg';
import compine from './images/compine.png';
import caltivetar from './images/cultivetar.png';
import hairo from './images/hairo.png';
import thresher from './images/paddy-thresher.jpeg';
import rotavetar from './images/rotavetar.png';

const serviceCategories = [
  {
    title: 'Agricultural Services',
    services: [
      {
        id: '1',
        name: 'Green Fields Co.',
        service: 'Tractor Rental and Maintenance',
        contact: '+91 11223 33445',
        image: tractor,
        cost: '2000 Rupees',
        timing: 'Whole Day',
        description: 'Green Fields Co. offers comprehensive tractor rental and maintenance services for your agricultural needs.',
      },
      {
        id: '2',
        name: 'AgroTech Solutions',
        service: 'Crop Management Consulting',
        contact: '+91 22334 44556',
        image: tractor,
        cost: 'Varies',
        timing: 'By Appointment',
        description: 'AgroTech Solutions provides expert consulting for effective crop management to enhance your yield.',
      },
      {
        id: '3',
        name: 'Farm Equipment Inc.',
        service: 'Farm Equipment Repair',
        contact: '+91 33445 55667',
        image: tractor,
        cost: 'Varies',
        timing: 'Business Hours',
        description: 'Farm Equipment Inc. specializes in the repair of various farm equipment to keep your operations running smoothly.',
      },
      {
        id: '4',
        name: 'Tractor Hub',
        service: 'New and Used Tractor Sales',
        contact: '+91 44556 66778',
        image: tractor,
        cost: 'Starting at 50000 Rupees',
        timing: 'Business Hours',
        description: 'Tractor Hub offers a wide range of new and used tractors for sale, catering to different agricultural needs.',
      },
      {
        id: '5',
        name: 'Harvest Helper',
        service: 'Harvesting Machinery Leasing',
        contact: '+91 55667 77889',
        image: tractor,
        cost: 'Varies',
        timing: 'Seasonal',
        description: 'Harvest Helper provides leasing options for harvesting machinery to streamline your harvest operations.',
      },
      {
        id: '6',
        name: 'Agri Supplies',
        service: 'Seeds and Fertilizers',
        contact: '+91 66778 88990',
        image: tractor,
        cost: 'Varies',
        timing: 'Business Hours',
        description: 'Agri Supplies offers a variety of seeds and fertilizers to meet the needs of different crops.',
      },
      {
        id: '7',
        name: 'Rural Services Ltd.',
        service: 'Irrigation System Installation',
        contact: '+91 77889 99001',
        image: tractor,
        cost: 'Varies',
        timing: 'By Appointment',
        description: 'Rural Services Ltd. installs efficient irrigation systems to ensure optimal water supply for your crops.',
      },
      {
        id: '8',
        name: 'Field Masters',
        service: 'Pest Control Services',
        contact: '+91 88990 10112',
        image: tractor,
        cost: 'Varies',
        timing: 'By Appointment',
        description: 'Field Masters provides pest control services to protect your crops from various pests and diseases.',
      },
      {
        id: '9',
        name: 'Soil & More',
        service: 'Soil Testing and Analysis',
        contact: '+91 99001 11223',
        image: tractor,
        cost: '1000 Rupees',
        timing: 'Business Hours',
        description: 'Soil & More offers soil testing and analysis to help you understand and improve soil quality for better crop yields.',
      },
      {
        id: '10',
        name: 'Tractor Pro',
        service: 'Tractor Training and Safety',
        contact: '+91 10112 22334',
        image: tractor,
        cost: '3000 Rupees',
        timing: 'Scheduled Sessions',
        description: 'Tractor Pro provides training and safety courses to ensure safe and effective tractor operation.',
      },
    ],
  },
  {
    title: 'Compines',
    services: [
      {
        id: '11',
        name: 'Plumb Perfect',
        service: 'Residential Plumbing',
        contact: '+91 12345 67890',
        image: compine,
        cost: 'Varies',
        timing: 'By Appointment',
        description: 'Plumb Perfect offers reliable residential plumbing services to address all your home plumbing needs.',
      },
      {
        id: '12',
        name: 'Electric Experts',
        service: 'Electrical Repairs and Installations',
        contact: '+91 23456 78901',
        image: compine,
        cost: 'Varies',
        timing: 'Business Hours',
        description: 'Electric Experts provides electrical repairs and installations to ensure your electrical systems are safe and functional.',
      },
      {
        id: '13',
        name: 'Carpentry Crew',
        service: 'Custom Carpentry',
        contact: '+91 34567 89012',
        image: compine,
        cost: 'Varies',
        timing: 'By Appointment',
        description: 'Carpentry Crew specializes in custom carpentry solutions for unique home and office needs.',
      },
      {
        id: '14',
        name: 'FixIt Fast',
        service: 'General Home Repairs',
        contact: '+91 45678 90123',
        image: compine,
        cost: 'Varies',
        timing: 'Business Hours',
        description: 'FixIt Fast offers prompt and efficient home repair services for a wide range of issues.',
      },
      {
        id: '15',
        name: 'Roof Rescue',
        service: 'Roof Repair and Maintenance',
        contact: '+91 56789 01234',
        image: compine,
        cost: 'Varies',
        timing: 'By Appointment',
        description: 'Roof Rescue provides expert roof repair and maintenance services to ensure the longevity and safety of your roof.',
      },
      {
        id: '16',
        name: 'Paint Pros',
        service: 'Interior and Exterior Painting',
        contact: '+91 67890 12345',
        image: compine,
        cost: 'Varies',
        timing: 'Scheduled',
        description: 'Paint Pros offers professional painting services for both interior and exterior surfaces, enhancing the look of your property.',
      },
      {
        id: '17',
        name: 'HVAC Heroes',
        service: 'Heating and Cooling Services',
        contact: '+91 78901 23456',
        image: compine,
        cost: 'Varies',
        timing: 'Business Hours',
        description: 'HVAC Heroes provides comprehensive heating and cooling services to maintain comfort in your home or business.',
      },
      {
        id: '18',
        name: 'Clean Air Ducts',
        service: 'Duct Cleaning Services',
        contact: '+91 89012 34567',
        image: compine,
        cost: '2000 Rupees',
        timing: 'Business Hours',
        description: 'Clean Air Ducts offers thorough duct cleaning services to improve air quality and system efficiency.',
      },
      {
        id: '19',
        name: 'Floor Fixers',
        service: 'Flooring Installation and Repair',
        contact: '+91 90123 45678',
        image: compine,
        cost: 'Varies',
        timing: 'By Appointment',
        description: 'Floor Fixers provides expert flooring installation and repair services for various types of flooring.',
      },
      {
        id: '20',
        name: 'Window Wizards',
        service: 'Window Replacement and Repair',
        contact: '+91 01234 56789',
        image: compine,
        cost: 'Varies',
        timing: 'Business Hours',
        description: 'Window Wizards offers professional window replacement and repair services to enhance your home’s appearance and energy efficiency.',
      },
    ],
  },
  {
    title: 'Cultivetor',
    services: [
      {
        id: '21',
        name: 'Sparkle Cleaners',
        service: 'Residential Cleaning',
        contact: '+91 11111 22222',
        image: caltivetar,
        cost: '1500 Rupees',
        timing: 'Flexible',
        description: 'Sparkle Cleaners offers high-quality residential cleaning services with attention to detail.',
      },
      {
        id: '22',
        name: 'Office Shine',
        service: 'Commercial Cleaning',
        contact: '+91 22222 33333',
        image: caltivetar,
        cost: '2000 Rupees',
        timing: 'Business Hours',
        description: 'Office Shine provides comprehensive commercial cleaning services to maintain a clean and professional workspace.',
      },
      {
        id: '23',
        name: 'Eco Clean',
        service: 'Eco-Friendly Cleaning',
        contact: '+91 33333 44444',
        image: caltivetar,
        cost: '1800 Rupees',
        timing: 'By Appointment',
        description: 'Eco Clean offers eco-friendly cleaning solutions to reduce environmental impact while maintaining cleanliness.',
      },
      {
        id: '24',
        name: 'Maid for You',
        service: 'Maid Services',
        contact: '+91 44444 55555',
        image: caltivetar,
        cost: '2500 Rupees',
        timing: 'Flexible',
        description: 'Maid for You provides professional maid services to assist with household chores and maintenance.',
      },
      {
        id: '25',
        name: 'Deep Clean Pros',
        service: 'Deep Cleaning Services',
        contact: '+91 55555 66666',
        image: caltivetar,
        cost: '3000 Rupees',
        timing: 'Scheduled',
        description: 'Deep Clean Pros specializes in thorough deep cleaning services for a fresh and hygienic environment.',
      },
      {
        id: '26',
        name: 'Carpet Care',
        service: 'Carpet Cleaning',
        contact: '+91 66666 77777',
        image: caltivetar,
        cost: '1200 Rupees',
        timing: 'By Appointment',
        description: 'Carpet Care offers professional carpet cleaning services to remove stains and rejuvenate your carpets.',
      },
      {
        id: '27',
        name: 'Window Gleam',
        service: 'Window Cleaning',
        contact: '+91 77777 88888',
        image: caltivetar,
        cost: '1000 Rupees',
        timing: 'Business Hours',
        description: 'Window Gleam provides expert window cleaning services to ensure clear and sparkling windows.',
      },
      {
        id: '28',
        name: 'Move Out Clean',
        service: 'Move-Out Cleaning',
        contact: '+91 88888 99999',
        image: caltivetar,
        cost: '3500 Rupees',
        timing: 'By Appointment',
        description: 'Move Out Clean offers thorough cleaning services for a smooth transition when moving out of a property.',
      },
      {
        id: '29',
        name: 'Sanitize Squad',
        service: 'Sanitization Services',
        contact: '+91 99999 00000',
        image: caltivetar,
        cost: '2200 Rupees',
        timing: 'Flexible',
        description: 'Sanitize Squad provides comprehensive sanitization services to ensure a hygienic environment.',
      },
      {
        id: '30',
        name: 'Laundry Lounge',
        service: 'Laundry and Dry Cleaning',
        contact: '+91 00000 11111',
        image: caltivetar,
        cost: 'Varies',
        timing: 'Business Hours',
        description: 'Laundry Lounge offers professional laundry and dry cleaning services for all types of garments.',
      },
    ],
  },
  {
    title: 'Hairo',
    services: [
      {
        id: '31',
        name: 'Green Thumb',
        service: 'Lawn Maintenance',
        contact: '+91 12345 12345',
        image: hairo,
        cost: '1000 Rupees',
        timing: 'Weekly',
        description: 'Green Thumb specializes in professional lawn maintenance to keep your garden looking pristine.',
      },
      {
        id: '32',
        name: 'Flower Power',
        service: 'Flower Bed Design',
        contact: '+91 23456 23456',
        image: hairo,
        cost: '1500 Rupees',
        timing: 'By Appointment',
        description: 'Flower Power offers expert flower bed design services to enhance the beauty of your garden.',
      },
      {
        id: '33',
        name: 'Tree Toppers',
        service: 'Tree Trimming and Care',
        contact: '+91 34567 34567',
        image: hairo,
        cost: '2000 Rupees',
        timing: 'Scheduled',
        description: 'Tree Toppers provides professional tree trimming and care services to maintain healthy and well-shaped trees.',
      },
      {
        id: '34',
        name: 'Landscape Legends',
        service: 'Landscape Design',
        contact: '+91 45678 45678',
        image: hairo,
        cost: 'Varies',
        timing: 'By Appointment',
        description: 'Landscape Legends offers creative landscape design services to transform your outdoor space.',
      },
      {
        id: '35',
        name: 'Irrigation Innovators',
        service: 'Irrigation System Installation',
        contact: '+91 56789 56789',
        image: hairo,
        cost: 'Varies',
        timing: 'By Appointment',
        description: 'Irrigation Innovators specializes in the installation of efficient irrigation systems to optimize water usage.',
      },
      {
        id: '36',
        name: 'Garden Gnomes',
        service: 'Garden Maintenance',
        contact: '+91 67890 67890',
        image: hairo,
        cost: '1200 Rupees',
        timing: 'Weekly',
        description: 'Garden Gnomes provides comprehensive garden maintenance services to keep your garden in top shape.',
      },
      {
        id: '37',
        name: 'Hedge Masters',
        service: 'Hedge Trimming',
        contact: '+91 78901 78901',
        image: hairo,
        cost: '800 Rupees',
        timing: 'By Appointment',
        description: 'Hedge Masters offers expert hedge trimming services to maintain the shape and health of your hedges.',
      },
      {
        id: '38',
        name: 'Pest Patrol',
        service: 'Garden Pest Control',
        contact: '+91 89012 89012',
        image: hairo,
        cost: 'Varies',
        timing: 'By Appointment',
        description: 'Pest Patrol provides effective garden pest control solutions to protect your plants from harmful pests.',
      },
      {
        id: '39',
        name: 'Soil Savvy',
        service: 'Soil Preparation',
        contact: '+91 90123 90123',
        image: hairo,
        cost: '1000 Rupees',
        timing: 'By Appointment',
        description: 'Soil Savvy offers soil preparation services to ensure the optimal condition of soil for planting.',
      },
      {
        id: '40',
        name: 'Veggie Growers',
        service: 'Vegetable Garden Planning',
        contact: '+91 01234 01234',
        image: hairo,
        cost: '1500 Rupees',
        timing: 'By Appointment',
        description: 'Veggie Growers specializes in planning vegetable gardens to maximize yield and efficiency.',
      },
    ],
  },
];

export default serviceCategories;
